#!/bin/sh

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#

remote="$1"
url="$2"

# Check rules on modified files
# tccdev/tools should be in $PATH

SCRIPT=check_all_rules.sh

if command -v $SCRIPT > /dev/null
then
	$SCRIPT
else
	echo "****************************************************"
	echo "Warning!"
	echo "$SCRIPT not found!"
	echo "Add <tccdev>/tools to the PATH to enable rules-checker"
	echo "****************************************************"
	exit -1
fi
