
/*******************************************************************************
INTEL CONFIDENTIAL
Copyright Intel Corporation.
This software and the related documents are Intel copyrighted materials, and your use of them
is governed by the express license under which they were provided to you (License).
Unless the License provides otherwise, you may not use, modify, copy, publish, distribute, disclose
or transmit this software or the related documents without Intel's prior written permission.
This software and the related documents are provided as is, with no express or implied warranties,
other than those that are expressly stated in the License.

*******************************************************************************/


// THIS IS AUTOGENERATED FILE. PLEASE DON'T EDIT.

#ifndef TCC_MSR_MOCK_HPP
#define TCC_MSR_MOCK_HPP

#include <tcc_msr.h>
#include <gmock/gmock.h>
#include <cstdarg>
#include "mock_common.hpp"

class tcc_msr_mock
{
public:
    MOCK_METHOD3(rdmsr,int(uint32_t reg, uint8_t cpu, uint64_t* data));
    MOCK_METHOD3(wrmsr,int(uint32_t reg, uint8_t cpu, const uint64_t* data));

    COMMON_MOCK_INTERFACE_DEFINITIONS_EXT(tcc_msr_mock)
};

extern "C"
{
    int __real_rdmsr(uint32_t reg, uint8_t cpu, uint64_t* data);
    int __real_wrmsr(uint32_t reg, uint8_t cpu, const uint64_t* data);
}

#endif // TCC_MSR_MOCK_HPP
