#!/bin/sh
### BEGIN INIT INFO
# Provides: TeamCity Build Agent
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start build agent daemon at boot time
# Description: Enable service provided by daemon.
### END INIT INFO

# How to use:
# 1) Copy this script to /etc/init.d/buildAgent
# 2) Update paths to TeamCity agents folders
# 3) Make the script executable and install it into the boot sequence:

##   chmod 755 /etc/init.d/buildAgent
##   update-rc.d buildAgent defaults

#Provide the correct user name:
USER="tccbuild"
case "$1" in
start)
 su - $USER -c "/opt/buildAgent_nnltccsrv-02/bin/agent.sh start ;\
/opt/buildAgent_nnltccsrv-02-quick1/bin/agent.sh start ;  \
/opt/buildAgent_nnltccsrv-02-quick2/bin/agent.sh start ; \
/opt/buildAgent_nnltccsrv-02-quick3/bin/agent.sh start"
;;
stop)
 su - $USER -c "/opt/buildAgent_nnltccsrv-02/bin/agent.sh stop ; \
/opt/buildAgent_nnltccsrv-02-quick1/bin/agent.sh stop ; \
/opt/buildAgent_nnltccsrv-02-quick2/bin/agent.sh stop ; \
/opt/buildAgent_nnltccsrv-02-quick3/bin/agent.sh stop"
;;
*)
 echo "usage start/stop"
 exit 1
 ;;
esac
exit 0
