
/*******************************************************************************
INTEL CONFIDENTIAL
Copyright Intel Corporation.
This software and the related documents are Intel copyrighted materials, and your use of them
is governed by the express license under which they were provided to you (License).
Unless the License provides otherwise, you may not use, modify, copy, publish, distribute, disclose
or transmit this software or the related documents without Intel's prior written permission.
This software and the related documents are provided as is, with no express or implied warranties,
other than those that are expressly stated in the License.

*******************************************************************************/


// THIS IS AUTOGENERATED FILE. PLEASE DON'T EDIT.

#ifndef TCC_MSR_MOCK_HPP
#define TCC_MSR_MOCK_HPP

#include <ittnotify/ittnotify.h>
#include <gmock/gmock.h>
#include "mock_common.hpp"

class itt_notify_mock
{
public:
    MOCK_METHOD1(__itt_domain_create, __itt_domain*(const char*));
    MOCK_METHOD1(__itt_string_handle_create, __itt_string_handle*(const char*));
    MOCK_METHOD4(__itt_task_begin, void(const __itt_domain *domain,__itt_id taskid, __itt_id parentid, __itt_string_handle *name));
    MOCK_METHOD1(__itt_task_end, void(const __itt_domain *domain));

    COMMON_MOCK_INTERFACE_DEFINITIONS_EXT(itt_notify_mock)
};

#endif // TCC_MSR_MOCK_HPP
